version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
      - terraform plan
  build:
    commands:
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Waiting for 5 minutes before destroying the deployment
      - sleep 300
      - echo Destroying Deployment
      - terraform destroy -auto-approve
 
artifacts:
  files:
    - '**/*'
  discard-paths: yes