version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv teffarform /usr/local/bin/
      - terraform --version
  pre-build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
      - echo "Validating Terraform template"
      - terraform validate
      - echo "Formatting Terraform template"
      - terraform fmt -recursive
  build:
    commands:
      - echo "Terraform plan for resource creation"
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo "Applying Terraform template"
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - "**/*"
  discard-paths: no
  
  